### ISSUE TITLE
Error when uploading to app store

### ISSUE THREAD

**Issue by haydursek** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#29] opened 2019-05-23 03:24 UTC
I am trying to upload our app to the appstore and encountering the following problem:

```
App Store Connect Operation Error
ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '2.1.13-swift4.2' in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"

App Store Connect Operation Error
ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '3.5.5-swift-4.2' in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"
```

I have tried adding a script to fix the version string as below, but that didnt seem to fix the issue. We need this resolved ASAP as we would like to push to the store by Friday. Please advise.

https://github.com/CocoaPods/CocoaPods/issues/4421#issuecomment-151804311

**Comment by jakubdolejs** [comment] 2019-05-23 08:39
Hello @haydursek,
• Open **platforms/ios/Pods/Ver-ID-Credentials/VerIDCredentials.framework/Info.plist** inside your project folder and change the value for the `CFBundleShortVersionString` key to `2.1.13`
• Open **platforms/ios/Pods/Ver-ID/VerID.framework/Info.plist** inside your project folder and change the value for the `CFBundleShortVersionString` key to `3.5.5`

**Comment by haydursek** [comment] 2019-05-23 23:31
Hi @jakubdolejs 
We need an automated way of changing this, or for you to have it output the correct bundle version during the install. We cannot do this by hand when we have to do builds, since we have an automated process. Please let me know if you have any other way of accomplishing this.

**Comment by jakubdolejs** [comment] 2019-05-24 09:31
Hi @haydursek,
No problem. We will publish it as a different CocoaPods project and let you know when it's available.
Jakub

**Comment by jakubdolejs** [comment] 2019-05-24 11:48
Hello @haydursek,

The issue is fixed in ab7eecb8baf9455e8a6d02e282a28105d871616b. We published a new pod called Ver-ID-Credentials-Swift4.2.

In the plugin.xml the line
```xml
<framework src="Ver-ID-Credentials" type="podspec" spec="2.1.13-swift4.2" />
```
has changed to:
```xml
<framework src="Ver-ID-Credentials-Swift4.2" type="podspec" spec="2.1.13" />
```

**Closed by jakubdolejs** 2019-05-24 11:48 UTC

**Comment by haydursek** [comment] 2019-05-25 01:23
@jakubdolejs So what steps do we need to do to get this new version ? Do we have to reinstall the plugin  or just do a pod update ?

**Comment by jakubdolejs** [comment] 2019-05-25 10:23
You can either pull the commit ab7eecb8baf9455e8a6d02e282a28105d871616b or change the line in the plugin.xm as indicated in the previous message. You’ll have to run `pod install` after that. 

The credentials pod has a dependency on the other library and it will bring it in with the pod install.
